declare module 'design-system/Button'
declare module 'design-system/StyleProvider'
declare module 'design-system/Modal'
declare module 'design-system/Text'
declare module 'design-system/Container'
declare module 'design-system/Card'
declare module 'core'